# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_test_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
